# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-27 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='category',
        ),
    ]
